const ERROR_KEY = {
  BATCH_SIZE_INVALID: 'errors.BATCH_SIZE_INVALID',
  FILE_TOO_LARGE: 'errors.FILE_TOO_LARGE',
  DAILY_QUOTA_EXCEEDED: 'errors.DAILY_QUOTA_EXCEEDED',
  IDEMPOTENCY_CONFLICT: 'errors.IDEMPOTENCY_CONFLICT',
  BATCH_NOT_ADMITTABLE: 'errors.BATCH_NOT_ADMITTABLE',
  BATCH_TOKEN_MISMATCH: 'errors.BATCH_TOKEN_MISMATCH',
  FILE_NOT_MEASURED: 'errors.FILE_NOT_MEASURED',
  NO_FILES_ADMITTED: 'errors.NO_FILES_ADMITTED',
  BATCH_MALFORMED: 'errors.BATCH_MALFORMED',
  ENTITLEMENTS_UNAVAILABLE: 'errors.ENTITLEMENTS_UNAVAILABLE',
  NOT_FOUND: 'errors.NOT_FOUND',
  TOO_MANY_REQUESTS: 'errors.TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE: 'errors.SERVICE_UNAVAILABLE',
  NETWORK_ERROR: 'errors.NETWORK_ERROR',
  STORAGE_REJECTED: 'errors.STORAGE_REJECTED',
  STORAGE_UNREACHABLE: 'errors.STORAGE_UNREACHABLE',
} as const;

const GENERIC_ERROR_KEY = 'errors.generic';

export { ERROR_KEY, GENERIC_ERROR_KEY };
